import type { LucideIcon, LucideProps } from "lucide-react";
import {
  BarChart3,
  Calendar,
  Check,
  CheckCircle,
  Clock,
  Coffee,
  Eye,
  FileText,
  Globe,
  GraduationCap,
  Home,
  Instagram,
  Lightbulb,
  Linkedin,
  Mail,
  Map,
  MapPin,
  PenTool,
  Phone,
  Quote,
  Rocket,
  Search,
  Send,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Star,
  Stethoscope,
  Target,
  TrendingUp,
  Twitter,
  Wrench,
  Zap,
} from "lucide-react";
import type { IconName } from "@/lib/cms-types";

export const CONTENT_ICONS: Record<IconName, LucideIcon> = {
  instagram: Instagram,
  linkedin: Linkedin,
  twitter: Twitter,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  search: Search,
  "shopping-cart": ShoppingCart,
  "share-2": Share2,
  "pen-tool": PenTool,
  "bar-chart-3": BarChart3,
  globe: Globe,
  target: Target,
  lightbulb: Lightbulb,
  eye: Eye,
  "trending-up": TrendingUp,
  rocket: Rocket,
  calendar: Calendar,
  star: Star,
  zap: Zap,
  quote: Quote,
  check: Check,
  clock: Clock,
  send: Send,
  "check-circle": CheckCircle,
  coffee: Coffee,
  stethoscope: Stethoscope,
  home: Home,
  "graduation-cap": GraduationCap,
  wrench: Wrench,
  "shield-check": ShieldCheck,
  map: Map,
  "file-text": FileText,
};

export function ContentIcon({
  name,
  ...props
}: LucideProps & { name: IconName }) {
  const Icon = CONTENT_ICONS[name] ?? Zap;
  return <Icon aria-hidden focusable="false" {...props} />;
}
